name: Sync Fork

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: pull
        run: |
          get pull https://github.com/awslabs/smithy.git
          git push
      - name: tag
        run: |
          git fetch --tags https://github.com/awslabs/smithy.git
          git push --tags
